# после изменения насроек, в консоли:
# sudo systemctl restart inosatiot_influxdb_mirror.service

hosts:
  - &src
    url: http://localhost:8086
    org: _org_
    token: _token_
  - &dst
    url: http://192.168.100.74:8086
    org: _org_
    token: _token_


mirroring:
  - src_host: *src
    src_bucket: inosatiot_resources_sim
    dst_host: *dst
    dst_bucket: inosatiot_resources_sim


downsampling:
  - src_host: *src
    src_bucket: inosatiot_resources_sim
    dst_host: *src
    dst_bucket_base: inosatiot_resources_sim
    intervals: [3m, 30m, 1d]